### ISSUE TITLE
Breaks when used with django-reversion

### ISSUE THREAD

**Issue by andybak** [greyside/django-admin-smoke-tests#1]
Still trying to track down exactly why but:
1. reversion's changelist_view calls reverse on some urls it defines in it's own get_urls
2. the ModelAdmin.get_urls is never called as AdminSite's _registry is empty when it hits this line:
   
   for model, model_admin in six.iteritems(self._registry):

(that's in contrib.admin.sites)

This is on Django 1.6 and reversion 1.8.5 - I'll test on Django 1.8 but the main reason I'm trying to get this working is to help with a big 1.6 > 1.8 upgrade!

**Comment by SeanHayes** [comment]
This is _might_ be due to django-reversion defining its own admin class.

Are your ModelAdmins or VersionAdmins registered? Are they registered using the default AdminSite, or are you defining a custom AdminSite?
https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#discovery-of-admin-files

**Comment by SeanHayes** [comment]
Try subclassing AdminSiteSmokeTest and manually specifying "modeladmins" with a list of 2 element tuples:

from django_admin_smoke_tests.tests import AdminSiteSmokeTest

class MyAdminSiteSmokeTest(AdminSiteSmokeTest):
    modeladmins = [(model, modeladmin)...]

**Comment by andybak** [comment]
I actually had to do:

```
modeladmins = [(Slideshow, SlideshowAdmin(Slideshow, admin.site))]
```

but in any case - same problem. Also tried on latest git version (before I was using pypi release)

I'll keep digging unless you've got any more ideas?

**Comment by andybak** [comment]
Found the problem. I'm doing this at the start of my root urls.py:

```
from .project_admin import ProjectAdminSite
admin.site = ProjectAdminSite()
```

which I swear was the recommended way at some point (probably Django 0.96!)

So I end up with two instances of admin.site - the one my models are being registered to, and the one that exists when smoketests run. I'd better figure out the correct way to override the normal AdminSite.

Amazed that this is the first time this has tripped me up in so long!
