### ISSUE TITLE
Make new PyPI version

### ISSUE THREAD

**Issue by PetrDlouhy** [greyside/django-admin-smoke-tests#13]
Please, make new PyPI version after Django 1.10 compatibility and other changes.

**Comment by SeanHayes** [comment]
I don't have the time to maintain this project. If you'd like, feel free to fork this project, and I can give you access on PyPi to upload a new version (I'll need your PyPi username).

**Comment by PetrDlouhy** [comment]
OK, my PyPI username is "petr.dlouhy". Thanks

**Comment by SeanHayes** [comment]
Done.

**Comment by PetrDlouhy** [comment]
@SeanHayes Thanks. I have uploaded the version 0.3.0 to PyPI. I don't have permissions for this repository, so please pull PR #14, which contains appropriate version changes to code.
