### ISSUE TITLE
get_absolute_url test will always fail for some models

### ISSUE THREAD

**Issue by andybak** [greyside/django-admin-smoke-tests#2]
This is probably more of a 'is this the right way to do it?' question rather than an actual bug.

I've got a model with the following:

```
def get_absolute_url(self):
    return reverse('product', kwargs={'slug': self.slug})
```

and the following url entry:

```
url(r'^(?P<slug>[\w-]+)/$', 'products.views.product', name='product')
```

Running smoke tests naively always fails as smoke tests will call it with a model that has no slug field set and thus slug is equal to '' which doesn't match the above rule.

I can think of two ways to get round this:
1. Subclass smoke tests and alter test_get_absolute_url so it supplies a slug
2. Subclass smoke tests and supply a fixture
3. Alter my model so that slug has a default value
4. Alter my url rule to url(r'^(?P<slug>[\w-]*)/$', 'products.views.product', name='product') - \* instead of + will therefore match

1 and 2 mean that I'll need a different subclass for every model - this rather defeats the object of having a single generic smoketest for the admin

3 and 4 mean that I'm changing perfectly good code just to make a test pass which feels wrong too.

Is there another solution I've not thought of?

**Comment by andybak** [comment]
Here's another idea - the test should iterate through the model fields and look for subclasses on SlugField - if it finds one, it should instantiate the model with a random value for that field.

Some of my models have a url based on a field that aren't a subclass of slugfield however. I can't think of a generic solution short of randomly generating data for all models fields.

**Comment by andybak** [comment]
OK. Answering my own question (again) - I can set FIXTURE_DIRS to a dir only if tests are running.

But then test_get_absolute_url would have to be something like:

```
def test_get_absolute_url(self):
    for model, model_admin in self.modeladmins:
        if hasattr(model, 'get_absolute_url'):
            instance = model.objects.first()
            if not instance:
                instance = model(id=1)
            url = instance.get_absolute_url()
```

Is that a change that you'd consider including?

**Comment by SeanHayes** [comment]
Yeah, I'd be fine with that, submit a PR.

In test_project, add a new model that uses a slug, get_absolute_url, etc. like you've described, and add a fixture file.

**Comment by andybak** [comment]
I've got that working.

I was planning to set FIXTURES_DIRS in my test_settings.py and use autoloading of inital_data. However initial_data is deprecated since 1.7 so I had another think.

I decided to add:

```
fixtures = ['django_admin_smoke_tests']
```

directly to AdminSiteSmokeTest. My thinking here is that it's a sensible default and you can always override it in a subclass if you don't like it. Any objections?

I'm a bit stuck on getting this plugged into your test project as 'main' isn't listed in INSTALLED_APPS so as far as I can tell, smoke tests is only testing auth.group and auth.user

And if I add 'test_project.main' to INSTALLED_APPS I get model validation errors.

Have I missed something?

**Comment by andybak** [comment]
Any word on this? I'll have a bash at fixing up the tests if you can just let me know I'm not being stupid here.

**Comment by SeanHayes** [comment]
Just pushed some fixes, sorry about that.

**Comment by SeanHayes** [comment]
I updated the code and the README with another new solution.

**Comment by andybak** [comment]
Was the solution for this excluding apps from smoke tests? Or have I misunderstood.

I was really close to a proper solution - it was only this question: https://github.com/greyside/django-admin-smoke-tests/issues/2#issuecomment-112153317

that was still outstanding.

**Comment by SeanHayes** [comment]
The best solution is to add fixtures with valid data for that model.
